apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-app-pipeline
spec:
  params:
    - name: repo-url
      description: "URL of the Git repository"
    - name: dockerfile-path
      description: "Path to the Dockerfile"
  tasks:
    - name: test-go-app
      taskRef:
        name: test-go-app
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: dockerfile-path
          value: "$(params.dockerfile-path)"
