# name: go-docker

# on:
#   push:
#     branches:
#       - master

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run Unit Tests
#         run: go test

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USER_NAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Build and push Docker images
#         id: docker_build
#         uses: docker/build-push-action@v2.3.0
#         with:
#           push: true
#           tags: |
#            dikshasahu/golang:latest
#           build-args: |
#             VERSION=main

name: go-docker

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: go test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Print workspace contents
        run: ls -R ${{ github.workspace }}



      - name: Build Docker image
        run: docker build . -t golang:1.16 -f Dockerfile
        working-directory: ${{ github.workspace }}

      - name: tag docker image 
        run: docker tag golang:1.16 dikshasahu/golang:latest

      - name: Run Dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: 'golang:1.16:latest'
          format: 'json'
          output: 'dockle_result.json'
          exit-code: '1'
          exit-level: 'warn'
         

      - name: Upload Dockle Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Dockle-Report
          path: dockle_result.json

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: |
            dikshasahu/golang:latest
          build-args: |
            VERSION=main

