# name: go-docker

# on:
#   push:
#     branches:
#       - master

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run Unit Tests
#         run: go test

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USER_NAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Build and push Docker images
#         id: docker_build
#         uses: docker/build-push-action@v2.3.0
#         with:
#           push: true
#           tags: |
#            dikshasahu/golang:latest
#           build-args: |
#             VERSION=main

name: go-docker

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: go test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2.3.0
        with:
          push: false
          tags: |
            dikshasahu/golang:latest
          build-args: |
            VERSION=main
      - name: Print directory structure
        run: ls -R

 


      - name: Run Trivy
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir aquasec/trivy dikshasahu/golang:latest

